### ISSUE TITLE
Expose `Error` in 0.3.0

### ISSUE THREAD

**Issue by lvaccaro** [laanwj/cln4rust#106]
In `v0.2.0` the `pub enum Error` are defined in `error.rs` file included in the `clightningrpc`, and I can import in my example by `clightningrpc::Error`.

In the following releases, the `error.rs` file is moved inside `common` subfolder, but it looks no public exposed from `clightningrpc`. A fast fix could be mark as public the following line
`pub use clightningrpc_common::errors::Error;` in `lightningrpc`. So I could import the `enum Error` in my example by `clightningrpc::lightningrpc::Error`.

**Comment by vincenzopalazzo** [comment]
uuh! refactoring is bad, thanks for reporting it

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/laanwj/cln4rust/pull/107

Thanks!
