### ISSUE TITLE
move the json utils inside the common crate

### ISSUE THREAD

**Issue by vincenzopalazzo** [laanwj/cln4rust#57]
we have a common crate that is built for sharing common implementation through other cartes, the `json_utils::init_payload()` inside the plugin should be moved into the common crate

**Comment by swaptr** [comment]
I think instead of just the `json_utils::init_payload()` we should probably consider moving the `plugin/commands/json_utils.rs` to the common crate? Don't you think it makes more sense to keep all the JSON utilities available for all the crates.

**Comment by vincenzopalazzo** [comment]
Yes this was the idea, move all the utils function inside the common crate
